### PR TITLE
task 3

### PR DESCRIPTION
**Pull request by Sneha-2000-kkr**
https://github.com/Sneha-2000-kkr/github_series/files/4779921/introduction.txt

https://github.com/Sneha-2000-kkr/github_series/files/4779931/solution.txt

### CODE REVIEW

**Comment by codewayy** [comment]
Don't update the readme. Move your file inside the name of your directory. Please update your work.

**Comment by Sneha-2000-kkr** [comment]
pull request

**Comment by kushagra-18** [comment]
Perfect

**Comment by codewayy** [comment]
Resolve the merge conflicts.

**Pull request closed without merging**
