### PR TITLE
New brch

### PR DESCRIPTION
**Pull request by yash3110**
The day 3 task. New branch with edit.

### CODE REVIEW

**Comment by absaditi6** [comment]
👍

**Comment by codewayy** [comment]
@yash3110 You need to add both files inside the name of your directory. Please read the docs properly. Have a good PR name and commit message. 
Same comments for your other PR too.

**Comment by codewayy** [comment]
@yash3110 Update your PR please.

**Comment by yash3110** [comment]
> @yash3110 Update your PR please.

@codewayy upadted my PR . please check

**Comment by yash3110** [comment]
@codewayy  https://github.com/codewayy/github_series/pull/32

**Pull request closed without merging**
